owner: kubernetes
repo: kops
assets:
  - source: darwin/amd64/kops
    githubName: kops-darwin-amd64
  - source: darwin/amd64/kops.sha256
    githubName: kops-darwin-amd64.sha256
  - source: darwin/arm64/kops
    githubName: kops-darwin-arm64
  - source: darwin/arm64/kops.sha256
    githubName: kops-darwin-arm64.sha256
  - source: linux/amd64/kops
    githubName: kops-linux-amd64
  - source: linux/amd64/kops.sha256
    githubName: kops-linux-amd64.sha256
  - source: linux/arm64/kops
    githubName: kops-linux-arm64
  - source: linux/arm64/kops.sha256
    githubName: kops-linux-arm64.sha256
  - source: windows/amd64/kops.exe
    githubName: kops-windows-amd64
  - source: windows/amd64/kops.exe.sha256
    githubName: kops-windows-amd64.sha256
  - source: linux/amd64/nodeup
    githubName: nodeup-linux-amd64
  - source: linux/amd64/nodeup.sha256
    githubName: nodeup-linux-amd64.sha256
  - source: linux/arm64/nodeup
    githubName: nodeup-linux-arm64
  - source: linux/arm64/nodeup.sha256
    githubName: nodeup-linux-arm64.sha256
  - source: linux/amd64/protokube
    githubName: protokube-linux-amd64
  - source: linux/amd64/protokube.sha256
    githubName: protokube-linux-amd64.sha256
  - source: linux/arm64/protokube
    githubName: protokube-linux-arm64
  - source: linux/arm64/protokube.sha256
    githubName: protokube-linux-arm64.sha256
  - source: linux/amd64/channels
    githubName: channels-linux-amd64
  - source: linux/amd64/channels.sha256
    githubName: channels-linux-amd64.sha256
  - source: linux/arm64/channels
    githubName: channels-linux-arm64
  - source: linux/arm64/channels.sha256
    githubName: channels-linux-arm64.sha256
  - source: images/images.tar.gz
    githubName: images.tar.gz
  - source: images/images.tar.gz.sha256
    githubName: images.tar.gz.sha256
