# netlify configuration
[build]
publish = "site"
command = "make build-docs-netlify"
# available here https://github.com/netlify/build-image/blob/xenial/included_software.md#languages
environment = { PYTHON_VERSION = "3.7" }